### ISSUE TITLE
Milestone2 Peer Review Activity

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/DSCI_522_BlackFriday_Purchases_Analysis#38]
**Visualization**

- More descriptive Figure and table captions.  **DONE**

**Quality -- Robustness and Maintainability**

- R libraries version included. **DONE**

**Quality -- Readability and Documentation**
- Add comma to the number of 500 000 so that is more readable 500, 000. **DONE**

**Grammar and Spelling**
- Spelling and grammar check. **DONE**

**Comment by gilbertlei** [comment]
Here is what I got from today's peer review session: 
- Maybe add unit to the x-axis of the t-distribution plot? (from Bailey Lei)
- Make it clear what currency is the amount. (from Paul Vial) 
- In the null hypothesis, maybe mention "United States"? (from Paul Vial) 
- Maybe mention male spend more female in the conclusion? (from Bailey Lei)

**Comment by gilbertlei** [comment]
also add feedback from Tiffany: 
- move 'Team' section to the top of the README file.
- move 'Dependencies' section to the bottom of the README file.
- change 'Procure' to 'Usage'. 
- update the usage graph: "run_all.sh" t- "Make all".

**Comment by gilbertlei** [comment]
@mru4913 I agree with your comments on the four points I received from today's peer review session.
