### ISSUE TITLE
Final milestone TODO list 

### ISSUE THREAD

**Issue by mru4913** [UBC-MDS/DSCI_522_BlackFriday_Purchases_Analysis#49]
# DSCI 522
 
+ final project 
	+ dependency diagram (DONE)
	+ code of conduct (DONE by Gilbert)
	+ docker container and create a docker hub (Done by Gilbert and Albert)

+ Refinement - organize, update and maintain files.

**Comment by gilbertlei** [comment]
I created our version of Code of Conduct. please merge the latest pull request and review the content.

**Comment by mru4913** [comment]
I have created a docker image in the docker hub. Please check

**Comment by mru4913** [comment]
I organized file and update README.file in each subdirectory.

**Comment by mru4913** [comment]
All problems solved.
